# Use the latest official Nginx image as the base image
FROM nginx:latest

# Copy the custom Nginx configuration file from the local directory to the container
COPY proxy.conf /etc/nginx/conf.d/default.conf