# Use the latest version of Ubuntu asa the base image
FROM ubuntu:latest

# Update API package list
RUN apt-get update

# Upgrade all installed packages
RUN apt-get upgrade -y

# Set the command to run when the container starts
CMD echo "Hello, World!"